// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Refugio;

#nullable disable

namespace Refugio.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Refugio.Entities.Especie", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Especies");
                });

            modelBuilder.Entity("Refugio.Entities.Genero", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("Refugio.Entities.Mascota", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Edad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("EspecieId")
                        .HasColumnType("int");

                    b.Property<bool>("Esterilizado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Foto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TamañoId")
                        .HasColumnType("int");

                    b.Property<bool>("Vacunas")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("EspecieId");

                    b.HasIndex("GeneroId");

                    b.HasIndex("TamañoId");

                    b.ToTable("Mascotas");
                });

            modelBuilder.Entity("Refugio.Entities.Tamaño", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tamaños");
                });

            modelBuilder.Entity("Refugio.Entities.Mascota", b =>
                {
                    b.HasOne("Refugio.Entities.Especie", "Especie")
                        .WithMany("Mascota")
                        .HasForeignKey("EspecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Refugio.Entities.Genero", "Genero")
                        .WithMany("Mascota")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Refugio.Entities.Tamaño", "Tamaño")
                        .WithMany("Mascota")
                        .HasForeignKey("TamañoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especie");

                    b.Navigation("Genero");

                    b.Navigation("Tamaño");
                });

            modelBuilder.Entity("Refugio.Entities.Especie", b =>
                {
                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("Refugio.Entities.Genero", b =>
                {
                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("Refugio.Entities.Tamaño", b =>
                {
                    b.Navigation("Mascota");
                });
#pragma warning restore 612, 618
        }
    }
}
